export var Hospitals = [
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 2,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 3,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 4,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 5,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 6,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 7,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 8,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 9,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 10,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 11,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 12,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 13,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 14,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 15,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 16,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 17,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 18,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 19,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 20,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 21,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 22,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 23,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 24,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    }
 ]

export var Doctors = [
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 13,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 41,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 51,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 61,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 21,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 341,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 15,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 3451,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1543,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 167,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 671,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    }

 ]

 export var Jobs = [
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    }

 ]