export var Hospitals = [
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    },
    {
        hID: 1,
        name: "Medicity",
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        phone: 9988776655,
        email: "medicity@med.com",
        website: "mymedicity.com",
        regNo: 3342
    }
 ]

export var Doctors = [
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    },
    {
        hID: 1,
        firstName: "Ankit",
        lastName: "Sharma",
        email: "ankit@gmail.com",
        phone: 9988776655,
        address: "dem street, chennai, India",
        state: "Chennai",
        city: "demo",
        pincode: 123456,
        age: 30,
        regNo: 3342,
        gender: 'M',
        dob: "02/09/1983",
        speciality: "cardiology"
    }

 ]

 export var Jobs = [
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    },
    {
        jID: 1,
        hID: 1,
        dID: 1,
        hospitalName: "medicity",
        hospitalAddress: "dem street, chennai, India",
        hospitalState: "Chennai",
        hospitalCity: "demo",
        hospitalEmail: "ankit@gmail.com",
        hospitalPhone: 9988776655,
        hospitalPincode: 123456,
        specialityReqd: "cardiology",
        jobDate: "09/07/2022",
        available: true,
        details:"Urgent doctor needed",
        pay: 20000
    }

 ]